### ISSUE TITLE
Linux AppImage does not recognize qt-openzwavedatabase.rcc

### ISSUE THREAD

**Issue by uSpike** [OpenZWave/ozw-admin#18]
When I try to run the appimage from http://bamboo.my-ho.st/bamboo/browse/OZW-OZW-84/artifact/JOB1/Linux---AppImage/OZWAdmin-0.1-x86_64.AppImage on my Ubuntu 18.04 machine:
```
ozwadmin: Deploying OZW Database to  "/home/jordan/.local/share/OpenZWave/ozw-admin"
ozw.database: Testing  "./qt-openzwavedatabase.rcc"
ozw.database: Testing  "../../qt-openzwave/qt-openzwavedatabase//qt-openzwavedatabase.rcc"
ozw.database: Testing Standard Paths "/home/jordan/.local/share/OpenZWave/qt-openzwavedatabase.rcc"
ozw.database: Testing Standard Paths "/usr/share/ubuntu/OpenZWave/qt-openzwavedatabase.rcc"
ozw.database: Testing Standard Paths "/usr/local/share/OpenZWave/qt-openzwavedatabase.rcc"
ozw.database: Testing Standard Paths "/usr/share/OpenZWave/qt-openzwavedatabase.rcc"
ozw.database: Testing Standard Paths "/var/lib/snapd/desktop/OpenZWave/qt-openzwavedatabase.rcc"
```
Then I get a popup error stating that "qt-openzwavedatabase.rcc" could not be found.

I inspected the AppImage squashfs, which does include `squashfs-root/usr/share/OpenZWave/qt-openzwavedatabase.rcc`

If I move `qt-openzwavedatabase.rcc` into the same directory as the AppImage and where I execute it from, the program launches fine.

**Comment by Fishwaldo** [comment]
Could you please retest with the latest versions and let me know?

**Comment by uSpike** [comment]
This is all good now.  Thanks for everything you're doing!
