### ISSUE TITLE
OSX image fails to build

### ISSUE THREAD

**Issue by yolani** [OpenZWave/ozw-admin#20]
Following compile errors appear on your CI:

/Users/fish/bamboo-agent-home/xml-data/build-dir/OZW-OZW-MAC/open-zwave/cpp/src/command_classes/Configuration.cpp:126:45: error: format specifies type 'unsigned short' but the argument has type 'uint8' (aka 'unsigned char') [-Werror,-Wformat]

What ever gets placed in the final dmg can not be started.

**Comment by Fishwaldo** [comment]
That has already been fixed, but I didn't trigger a rebuild. Happening now.
