### ISSUE TITLE
Create a "recognized" Windows installer

### ISSUE THREAD

**Issue by kpine** [OpenZWave/ozw-admin#28]
When using the Windows installer, a scary warning is produced because of an "unrecognized app":

![image](https://user-images.githubusercontent.com/791794/82587631-61df4d00-9b4e-11ea-8437-ca74069f3ceb.png)

Windows complains, I presume, because the publisher is unverified, maybe for more reasons. Installing requires clicking on More Info.

![image](https://user-images.githubusercontent.com/791794/82587749-98b56300-9b4e-11ea-8e5a-3797766198fa.png)

Do whatever is necessary to make Windows happy.

**Comment by Fishwaldo** [comment]
I need to investigate whats required for this. I imaging purchasing a certificate etc from *somewhere* and signing the packages etc.

**Comment by kpine** [comment]
From my one or two minutes of searching, it sounds like you need a "Code Signing Certificate". To get past the Microsoft Defender SmartScreen warning, your application also needs to either earn "reputation", or you can bypass that by upgrading an EV Code Signing Cert.

Sounds expensive and a pain in the butt.

**Comment by kpine** [comment]
Relevant article I saw today: https://getimageview.net/2020/06/02/microsoft-defender-smartscreen-is-hurting-independent-developers/

And Hacker News discussion: https://news.ycombinator.com/item?id=23392404

You can close this bug if you want, I'll be using to the bundled allinone docker image myself. A portable install package would avoid this as well. It sounds like going through the Windows Store _might_ make it verified, but who wants to use that?
