### ISSUE TITLE
Mac OS app not for 10.13 and lower

### ISSUE THREAD

**Issue by balk77** [OpenZWave/ozw-admin#31]
I just tried to install this on my 2011 Macbook pro which does not support Mac OS beyond High Sierra (10.13). Unfortunately the OZW Admin app is not compatible with 10.13 or lower. Is this because of something specific introduced after 10.13 or is it a compilation setting?

I was also wondering if there is a web-app in your planning?

**Comment by Fishwaldo** [comment]
I'll have a look into supporting older versions of Mac soon. Really not sure what dependencies it has on OSX right now, and its just using the default backwards compat that my build systems are configured for.

**Comment by Fishwaldo** [comment]
Could you please try Build 108 when it appears and see if it works on your OSX?

**Comment by balk77** [comment]
> Could you please try Build 108 when it appears and see if it works on your OSX?

It runs! Thanks a lot :) 
Does this limit functionality or make compilation less straightforward?
