### ISSUE TITLE
Increment version number and/or add other build properties to version info

### ISSUE THREAD

**Issue by kpine** [OpenZWave/ozw-admin#34]
Per #21 there is now a launch splash screen and About dialog that show the OZW Admin version. However, the version is pinned to "0.1.0" so it's not very useful.

Consider adding some other properties besides a version number, such as date of build, Git commit SHA, and build number. The last one would be most useful for users as it refers back to a specific downloaded [artificat](http://bamboo.my-ho.st/bamboo/browse/OZW-OZW).

**Comment by Fishwaldo** [comment]
Everything is now versioned and released on GitHub Releases. (preview builds will still be on bamboo).
