### ISSUE TITLE
No config parameters available

### ISSUE THREAD

**Issue by yolani** [OpenZWave/ozw-admin#36]
Hi there,

i am using the following OZW-Admin Version omg MAC-OS 10.15.4

Versions:
OpenZWave Version 1.6.1133
qt-openzwave Version: 1.1.0
QT Version: 5.12.4

I can connect to the OpenZwave daemon on another host in my network and I see the notes, however I don't get any options for the config parameters.

<img width="1118" alt="parems" src="https://user-images.githubusercontent.com/219931/83443859-bcc84c80-a44a-11ea-82fb-6c0b747a7acf.png">

On the other hand, the tab with the node statistics seems fine.

Any idea what's going wrong?

-Christian

**Comment by Fishwaldo** [comment]
Do the Values appear in the MQTT?

Possibly related to #35

**Comment by yolani** [comment]
Can you tell me where in the topic structure they are supposed to be? On a first glimpse I don't see any, only a tree like this:
![image](https://user-images.githubusercontent.com/219931/83943614-d9bf9f80-a7fd-11ea-99b3-3347980bc621.png)

**Comment by Fishwaldo** [comment]
Config Params are just normal CommandClass Values. Search for CommandClass 112 under any node. If there isn't any - Your devices either don't have Config Options, or OZW couldn't properly load the config database (check the logs at startup of ozwdaemon)

**Comment by yolani** [comment]
Thanks for the hint, however command class 112 is present and the parameters still don‘t show up. 

<img width="534" alt="Bildschirmfoto 2020-06-12 um 08 24 34" src="https://user-images.githubusercontent.com/219931/84471892-95f9e980-ac86-11ea-9b44-fdf25e00240e.png">

Node 36 is a Fibaro Roller Shutter 3.

**Comment by yolani** [comment]
Well I am not sure if you have actively changed anything, but I just updated the qt-openzwave docker to the latest image as well as pulling the latest build of ozwadmin and everything is back to normal
<img width="1149" alt="Bildschirmfoto 2020-06-14 um 14 27 16" src="https://user-images.githubusercontent.com/219931/84593178-2e40cb80-ae4b-11ea-963d-93364847402e.png">

**Comment by Fishwaldo** [comment]
I'd say this is related to #35 

Latest GUI will warn you if the CACHE is too small after connecting. If you get that message, then we can confirm this was the issue and close this ticket.

**Comment by yolani** [comment]
I guess you are right, here is the popup:

<img width="453" alt="Bildschirmfoto 2020-06-16 um 05 49 56" src="https://user-images.githubusercontent.com/219931/84730096-956a9700-af95-11ea-89cd-6edf7d1f184d.png">

After increasing it to 1500 in the config it works again, although the application crashes / terminates itself after setting the config parameter. But it gets saved and is set to 1500 at the next start.

**Comment by Fishwaldo** [comment]
Ok. Closing this issue. I noticed the crash as well and will be pushing a fix for that shortly in #35.
