### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by kpine** [OpenZWave/ozw-admin#37]
The latest build seems to have resulted in high cpu usage. I am using the new allinone ozwdaemon image, which currently is ozwdaemon:allinone-build-9. I presume this is OZW Admin build 115. Upon connecting to ozwdaemon via VNC, ozwadmin is pegged at 100% and doesn't stop.

**Comment by tprelog** [comment]
I have a similar situation using ozw-admin build `115` appimage connecting to the latest ( pulled this morning ) `ozwdaemon` container.

The rpi 3B+ running `ozwdaemon` is at 25%-35% CPU ( single core ) and my computer running `ozw-admin` is using 70%-80% CPU ( single core ) -- Also there is sever response lag in the `ozw-admin` GUI when selecting between different devices -- [video clip](https://youtu.be/j9fftwuG0-Q)




Using `ozw-admin` build `111` with the latest `ozwdaemon` container seems to work as expected and all CPU usage is negligible

**Comment by Fishwaldo** [comment]
Yep. I’m aware. I need to refactor some code around the remote Logs. Will hopefully get that done tomorrow.

**Comment by Fishwaldo** [comment]
Should be fixed. It may get a bit laggy when there are lots of logs (OZW 1.7 will fix that with reduced logging) so you can hit the new "pause" button on the Logs window to stop it trying to scroll to new log entries.

Also improved the way Logs were sent to the remote clients which was also causing issues.
