### ISSUE TITLE
GUI hung on connection attempt at GotValueData 80%

### ISSUE THREAD

**Issue by michaelolson** [OpenZWave/ozw-admin#41]
This is on Windows 10.

Is there an easy way to pull logs for this process? I didn't see anything in EventViewer, the install directory, or my home directory.

I also have two hard crash reports that I can submit if that's helpful.

**Comment by raz0rf0x** [comment]
Also seeing the same issue. Also Windows 10. Attempting to connect remotely.

**Comment by Fishwaldo** [comment]
Right now, the Versions of ozwdaemon and ozw-admin are tightly coupled (as a lot of development work is going on right now on the Network aspects of the code). Suggest you run the allinone docker image of ozwdaemon and use VNC to use ozw-admin till such a time that the work has stabilized a bit

I did add a error message if there is a major change in the protocol between the two, but it might not catch a lot of "enhancements" that are going into the code right now.
