### ISSUE TITLE
Network Cache Size

### ISSUE THREAD

**Issue by keithmichael** [OpenZWave/ozw-admin#46]
When I start OZWAdmin (windows, build 145) I receive the following error after I establish a remote connection

Please increase the Network Cache Size in the configuration. Current Setting: 1000 Remote Max Records 1733

Steps I took: 
Restarted docker and the host system
Install same build on another Windows system

This also happened with an earlier build; I believe it was from this past Monday.

I'm using QT-ozw, all in one, and running 'latest'

Thanks for working on this project! 

![2020-06-17_20-35-55](https://user-images.githubusercontent.com/21224565/84964469-34001080-b0da-11ea-84b3-c61cbb694604.jpg)

**Comment by Fishwaldo** [comment]
As the dialog instructs you - please increase the value in the preferences window.

**Comment by Dinth** [comment]
@Fishwaldo sorry for replying on a closed thread, but im just trying to get this working on OSX version and theres no Network Cache Size setting in the Configuration window. Could you please advise how to adjust this?

**Comment by keithmichael** [comment]
It was under preference - File - Preferences
