### ISSUE TITLE
Windows installer choose a bad default installation directory

### ISSUE THREAD

**Issue by kpine** [OpenZWave/ozw-admin#47]
Just went and installed that 0.1.63 build downloaded from the github releases. When I run the installer, it chooses a bad path:

![image](https://user-images.githubusercontent.com/791794/85082909-15a31f00-b185-11ea-8f28-b30491f8d716.png)

Notice the paths is missing a backslash, `C:\Program Files (x86)OpenZwave Admin` instead of `C:\Program Files (x86)\OpenZwave Admin`. The installer from Build 142 does not have this problem.

**Comment by kpine** [comment]
Perhaps for the same root cause, the Start Menu shortcuts are also installed incorrectly. I ended up with a single shortcut called `ProgramsOpenZWaveOpenZwave AdminOpenZwave Admin` and an empty `OpenZWave` folder.

**Comment by Fishwaldo** [comment]
Such weird quoting rules in Qmake... can't wait to switch to cmake. (this was a fallout of the version tagging changes)
Will push a fix soon.

**Comment by Fishwaldo** [comment]
Should be fixed!
