### ISSUE TITLE
Windows installer does not add an entry for "Add/Remove Programs"

### ISSUE THREAD

**Issue by kpine** [OpenZWave/ozw-admin#48]
After installing in Windows, the Windows list of programs does not show the OpenZWave Admin application so it cannot be uninstalled from that location or by 3rd party uninstallers. Only the uninstaller shortcut from the start menu works.

In Windows 10, open the Settings App, go to Apps and look for OpenZWave Admin but find no entry. Normally the version and install date of a program is shown, with an option to uninstall. Or, use a 3rd party tool like Geek Uninstaller, and notice there is not an entry to uninstall the application.

I think it's always been like this, nothing new.

**Comment by Fishwaldo** [comment]
I have to see if the NSIS installer has a option enable this in Windows.

**Comment by kpine** [comment]
I think this has some relevant info: https://nsis.sourceforge.io/Add_uninstall_information_to_Add/Remove_Programs

I was poking around my system for some other OSS that use installers, came across Wireshark. https://github.com/wireshark/wireshark/blob/51bb2c4d7f515a24659ba0c0048392a81becda4e/packaging/nsis/wireshark.nsi#L822
