### ISSUE TITLE
Remove connection progress dialog stops at 30%

### ISSUE THREAD

**Issue by kpine** [OpenZWave/ozw-admin#5]
When connecting to a remote host, the connection progress dialog stops updating at exactly 30% ("OpenZWave Ready"), both on Linux and WIndows. I thought it was hung and left it running for tens of minutes. When I went to take a screenshot, the dialog was gone. I found that just hitting escape gets rid of the dialog and everything seems to be working normally.

This is on build 60. Previously I think I was using build 52 on Linux and there was no dialog, Windows did not even connect. Windows is working now.

Is submitting these kind of issues helpful? I know this is an early work in progress.

**Comment by Fishwaldo** [comment]
The progress dialog is “in progress” (pun intended!), but yes, the plan is to close it automatically when the connection is fully synced. (Also to display so updates for local connections). 

I have to work on the “percentages” still. 

This feedback is valuable - for one, I know builds are not breaking - but also any suggestions are welcome ;)

**Comment by Fishwaldo** [comment]
For Remote Connections - This should be better - and it auto closes once we are synced with the remote OZWDaemon.

For Local Connections - I still have todo some work there.
