### ISSUE TITLE
Can't add usercodes on BeNext panel

### ISSUE THREAD

**Issue by DieterKoblenz** [OpenZWave/ozw-admin#53]
Hi there,

I can't add usercodes to the benext panel. It displayers all user values, but once I've filled them in they are empty again.

![image](https://user-images.githubusercontent.com/2961896/88341134-51f60c00-cd3d-11ea-829a-bd056d29fbdb.png)

**Comment by DieterKoblenz** [comment]
I guess this is linked to issue #39

**Comment by Fishwaldo** [comment]
Correct - This is not fully supported yet. Merging with #39
