### ISSUE TITLE
Some GUI controls have non-standard behavior

### ISSUE THREAD

**Issue by kpine** [OpenZWave/ozw-admin#6]
When I click on a list item's pull-down menu there is no response. I need to double click on the control for it to show the list values. It should only require one click. Example: go to the "Node Configuration" tab for a node. Click on a value to change the parameter, it just selects the row instead of showing the available values.

Some controls are modifiable, but should be read only. Example: go to the "Node Status" tab for a node. Click on the "Sleeping" radio button. For a mains-powered device, the checkbox is set for a moment, then disappears.

**Comment by Fishwaldo** [comment]
> I need to double click on the control for it to show the list values. It should only require one click. 

Annoying right? :)

>Some controls are modifiable, but should be read only. Example: go to the "Node Status" tab for a node. Click on the "Sleeping" radio button. For a mains-powered device, the checkbox is set for a moment, then disappears.

I'll check that out. 

I'd like to make some sort of "visual" indicator for items that are editable... still thinking about that...

**Comment by kpine** [comment]
The node values also appear to be modifiable, even if they should be read-only. I can change them and the new values persist between remote sessions. It only seems to be affecting the OZW-admin side of things, it doesn't get reflected in the MQTT output. Some kind of caching issue? I noticed in the MQTT json data there are ReadOnly and WriteOnly flags for the values, set to false. Is that related to the nodes still being in CacheLoad?

Example: My door sensor has an Access Control value. I can double click the list and change it to any of the available choices (Open, Closed, Clear). If I close the application and re-connect, the values have persisted.

EDIT: I just changed a battery level! Free power! 😎

**Comment by kpine** [comment]
Here's a new one. With the UI re-design, all of the value-related columns (Label, etc) look to be auto-sized, however the Value column itself looks fixed, and cannot be resized, so the choices are unreadable. Probably want to allow resizing, and also some initial reasonable size.

![image](https://user-images.githubusercontent.com/791794/83043482-cb040c00-9ff7-11ea-8906-43d9598b6645.png)

**Comment by Fishwaldo** [comment]
Check the Latest Build - You can once again resize columns - but the default sizes are still not handling CheckBoxes etc correctly. That will come soon

**Comment by kpine** [comment]
Build 105?

**Comment by Fishwaldo** [comment]
Yep. Windows is still building as we speak.
