### ISSUE TITLE
Cannot set numeric config entries

### ISSUE THREAD

**Issue by matejdro** [OpenZWave/ozw-admin#68]
I'm trying to set numeric config entries on Nano Shutter here:

![image](https://user-images.githubusercontent.com/507922/94180997-20193700-fe9f-11ea-98b6-239d66d84ba4.png)

I double click on the field, enter any number (including trivial change like 151) and upon pressing enter, value just reverts to 150. According to Z-wave logs, nothing is being sent to the device, so it's not the device rejecting the change.

This particular config entry does not appear to be read-only: https://github.com/dooz127/open-zwave/blob/b583db0a1d8efa2b1793e4429641e22c61debfce/config/aeotec/zw141.xml#L61

Is this a bug or am I doing something wrong? This is with V0.1.74 on Manjaro Linux.

**Comment by kpine** [comment]
Duplicate of #39. Decimal values are not supported yet.

**Comment by matejdro** [comment]
Thanks for the info.

**Comment by kpine** [comment]
I just noticed this is a config value. Decimal is not even a valid config value type. You should probably fix the XML file so it's a short (2-byte integer).
