### ISSUE TITLE
Remember the details of the last remote host connection

### ISSUE THREAD

**Issue by kpine** [OpenZWave/ozw-admin#7]
This is an enhancement request to remember the last used remote connection details (probably should apply to Local settings as well, but I haven't tried those).

When I open the app and click "Open", the Remote Client details are defaulted to 127.0.0.1:1983 (the sections says Remote _Client_, should it be _Host_?). I enter my daemon's host name and click Start to connect. When I close the application and open it again, it forgets the server details and fills in the defaults. It would be convenient if the last entered values were saved, so I can just reconnect immediately.

Even better would be some kind of connection management dialog that allowed saving multiple hosts, but I personally have no need for that and would be happy just to have the last values remembered.

**Comment by Fishwaldo** [comment]
Done
